version: '3'

services:
  postgres-server:
    image: 'postgres:13.6'
    environment:
      - POSTGRES_PASSWORD=astrongpassword
      - POSTGRES_USER=apps
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata: {}